---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: yes

- name: Deploy web app content
  template:
    src:  "../../../../app/simple-web-app/templates/index.html"
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'
