variable "aws_region" {}
variable "vpc_cidr" {}
variable "public_subnet_cidr" {}
variable "availability_zone" {}
variable "vpc_name" {}
variable "sg_name" {}
variable "ami" {}
variable "instance_type" {}
variable "key_name" {}
variable "instance_name" {}
